#include "defconfig.h"

/* The base config the user owns. Written once, when it is missing, so a bare
   executable dropped into an empty folder has something to start from. It is
   never rewritten afterwards - from then on the file is the user's. */
const char utgard_default_config[] =
    "{\n"
    "  \"log\": {\n"
    "    \"level\": \"error\",\n"
    "    \"timestamp\": true,\n"
    "    \"output\": \"logs/sing-box.log\"\n"
    "  },\n"
    "\n"
    "  \"dns\": {\n"
    "    \"servers\": [\n"
    "      { \"tag\": \"local\", \"type\": \"local\" },\n"
    "      {\n"
    "        \"tag\": \"doh\",\n"
    "        \"type\": \"h3\",\n"
    "        \"server\": \"dns.google\",\n"
    "        \"server_port\": 443,\n"
    "        \"path\": \"/dns-query\",\n"
    "        \"domain_resolver\": \"local\"\n"
    "      }\n"
    "    ],\n"
    "    \"rules\": [\n"
    "      { \"rule_set\": [\"general\"], \"server\": \"doh\" }\n"
    "    ],\n"
    "    \"final\": \"local\",\n"
    "    \"strategy\": \"ipv4_only\"\n"
    "  },\n"
    "\n"
    "  \"inbounds\": [\n"
    "    {\n"
    "      \"type\": \"tun\",\n"
    "      \"tag\": \"tun-in\",\n"
    "      \"address\": [\"172.30.30.1/30\"],\n"
    "      \"mtu\": 1430,\n"
    "      \"auto_route\": true,\n"
    "      \"strict_route\": false,\n"
    "      \"stack\": \"system\"\n"
    "    }\n"
    "  ],\n"
    "\n"
    "  \"route\": {\n"
    "    \"auto_detect_interface\": true,\n"
    "    \"default_domain_resolver\": \"local\",\n"
    "    \"final\": \"direct\",\n"
    "    \"rules\": []\n"
    "  }\n"
    "}\n"
    "\n";

const size_t utgard_default_config_len = sizeof utgard_default_config - 1;
